spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pengmin123
    url: jdbc:mysql://127.0.0.1:3306/wechat-meal?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

#server: 8088

server:
  port: 8080
  context-path: /sell

wechat:
  mpAppId: wx3891fa5eb94ec618
  mpAppSecret: 9c9e25be8590199d62ba07a3d378b2a3

#  openAppId: wx6ad144e54af67d87
#  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
#  mchId: 1483469312
#  mchKey: 06C56A89949D617xxxxxxxxxxx
#  # 配置证书路径
#  keyPath: /var/weixin_cert/h5.p12
#  notifyUrl: http://minpeng.natapp4.cc/sell/pay/notify
#  templateId:
#      orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://minpeng.natapp1.cc
  wechatOpenAuthorize: http://minpeng.natapp1.cc
  sell: http://minpeng.natapp1.cc