spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pengmin123
    url: jdbc:mysql://127.0.0.1:3306/wechat-meal?characterEncoding=utf-8&useSSL=false
jpa:
  show-sql: true

server:8088
#server:
#  /wechat-meal